service: servicio-vuelos

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  environment:
    REVIEWS_TABLE: ${self:service}-${self:provider.stage}-resenas
  iam:
    role: arn:aws:iam::498917627164:role/LabRole

functions:
  crearResena:
    handler: crearResenia.handler
    events:
      - http:
          path: /resenias/crear
          method: post
          cors: true
          integration: lambda
  obtenerReseñas:
    handler: obtenerResenia.handler
    events:
      - http:
          path: /reviews
          method: get
          cors: true

resources:
  Resources:
    ReviewsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.REVIEWS_TABLE}
        AttributeDefinitions:
          - AttributeName: id_usuario
            AttributeType: S
          - AttributeName: id_resenia
            AttributeType: S
          - AttributeName: calificacion
            AttributeType: N  # Usado para el LSI
          - AttributeName: id_vuelo
            AttributeType: S  # Usado para el GSI
        KeySchema:
          - AttributeName: id_usuario
            KeyType: HASH
          - AttributeName: id_resenia
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

        # Índice Secundario Local (LSI)
        LocalSecondaryIndexes:
          - IndexName: CalificacionIndex
            KeySchema:
              - AttributeName: id_usuario
                KeyType: HASH
              - AttributeName: calificacion
                KeyType: RANGE
            Projection:
              ProjectionType: ALL

        # Índice Secundario Global (GSI)
        GlobalSecondaryIndexes:
          - IndexName: VueloIndex
            KeySchema:
              - AttributeName: id_vuelo
                KeyType: HASH
              - AttributeName: id_resenia
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5
